#!/usr/bin/env node
/**
 * neolit.nvim host shim.
 *
 * Embeds the neolit planned-diff kernel exactly the way the standalone TUI
 * does (AugmentTuiController + CliAgentRuntime, built from the neolit
 * package's dist/) and exposes the controller plus the TUI's pure view model
 * (dist/tui/detail.js) over newline-delimited JSON-RPC 2.0 on stdio, the same
 * framing augmentd uses. The Neovim side renders frames and routes keys; all
 * plan lifecycle, model runtime, apply/commit transactions, and view-model
 * derivation stay here, shared with the TUI.
 *
 * Every state-changing request responds with a fresh frame. Background
 * follow-ups (the automatic approach generation after a task starts) push
 * `neolit/progress` and `neolit/frame` notifications so an idle client still
 * repaints.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import readline from "node:readline";

const DEFAULT_SPINNER = "⠋";

function parseArguments(argv) {
  const options = { dist: undefined, directory: undefined, stubRuntime: false, noModel: false };
  for (let index = 0; index < argv.length; index++) {
    const argument = argv[index];
    if (argument === "--dist") options.dist = argv[++index];
    else if (argument === "--directory") options.directory = argv[++index];
    else if (argument === "--stub-runtime") options.stubRuntime = true;
    else if (argument === "--no-model") options.noModel = true;
  }
  return options;
}

function firstLine(value) {
  return String(value ?? "").split(/\r?\n/)[0] ?? "";
}

function rpcError(code, message) {
  return { code, message };
}

const args = parseArguments(process.argv.slice(2));
const dist = args.dist ?? process.env.NEOLIT_DIST;
if (!dist || !fs.existsSync(path.join(dist, "index.js"))) {
  process.stderr.write(`neolit host: no neolit dist at ${dist ?? "(unset)"}. Point --dist (or NEOLIT_DIST) at a neolit checkout with dist/ built (npm run build).\n`);
  process.exit(1);
}

const fromDist = (relative) => import(pathToFileURL(path.join(dist, relative)).href);
const { AugmentTuiController, CliAgentRuntime, candidatesForEntry } = await fromDist("index.js");
const { detailLines, entryName, entryState, entryTouchesNode, theme } = await fromDist("tui/detail.js");
const { effectiveConfig } = await fromDist("tui/config.js");
const { backendById } = await fromDist("tui/agent-backends.js");

function commandAvailable(command) {
  if (!command) return false;
  if (command.includes("/")) {
    try {
      fs.accessSync(command, fs.constants.X_OK);
      return true;
    } catch {
      return false;
    }
  }
  return (process.env.PATH ?? "").split(path.delimiter).some((directory) => {
    try {
      fs.accessSync(path.join(directory, command), fs.constants.X_OK);
      return true;
    } catch {
      return false;
    }
  });
}

/** Deterministic model runtime for tests: singleton domain → one file → a patch that appends a line to session.ts. */
const STUB_PATCH = "--- a/session.ts\n+++ b/session.ts\n@@ -1,2 +1,3 @@\n alpha\n beta\n+gamma\n";
const stubRuntime = {
  async call(request) {
    switch (request.operation) {
      case "generate-domain":
        return { value: { candidates: [{ label: "Edit session", rationale: "direct edit", confidence: 80, touchedPaths: ["session.ts"] }] } };
      case "challenge-domain":
        return { value: { kind: "accept" } };
      case "refine-node":
        return { value: { children: [{ kind: "file", path: "session.ts", lod: "hunk", reason: "apply the edit" }] } };
      case "draft-patch":
        return { value: { patch: STUB_PATCH, assumptions: [] } };
      default:
        throw new Error(`stub runtime: unexpected operation ${request.operation}`);
    }
  },
};

// Model availability mirrors bin/augment.tsx: env/flags > config file > defaults.
const config = effectiveConfig();
const modelDisabled = args.noModel || process.env.AUGMENT_TUI_NO_MODEL === "1";
const backend = backendById(config.backend ?? "opencode");
const requestedCommand = config.command ?? backend.defaultCommand;
const stub = args.stubRuntime;
const modelInfo = stub
  ? { available: true, label: "STUB" }
  : {
    available: !modelDisabled && commandAvailable(requestedCommand),
    label: config.model ?? `${backend.id} DEFAULT`.toUpperCase(),
  };

let controller;
let autoGenerated = new Set();

function write(message) {
  process.stdout.write(`${JSON.stringify(message)}\n`);
}

function respond(id, result) {
  write({ jsonrpc: "2.0", id, result });
}

function respondError(id, code, message) {
  write({ jsonrpc: "2.0", id, error: { code, message } });
}

function notify(method, params) {
  write({ jsonrpc: "2.0", method, params });
}

/**
 * One render frame: header chips, tree rows with per-segment colors (the same
 * PlannedRow composition as the Ink TUI), the two-section detail pane from
 * detailLines(), the message panel state, and the numbered approach choices
 * open on the selected row. Scrolling, cropping, and selection highlighting
 * belong to the client's windows.
 */
function buildFrame(spinner = DEFAULT_SPINNER) {
  const state = controller.snapshot();
  const selectedRow = controller.selectedRow();
  const live = state.active || state.failed
    ? { spinner, active: state.active, failed: state.failed }
    : undefined;

  const rootStatus = state.task?.nodes[state.task.rootNodeId]?.status;
  const status = state.busy
    ? "BUSY"
    : state.task?.mode === "explanation"
      ? Object.keys(state.task.explanations).length ? "EXPLAINED" : "EXPLAINING"
      : rootStatus ? rootStatus.toUpperCase() : "IDLE";
  const lockCount = state.task?.lockedPaths.length ?? state.pendingMarks.length;
  const lockMode = state.task?.restrictionMode ?? state.pendingMode;

  const header = {
    left: [
      { text: "NEOLIT", color: theme.primary, bold: true },
      { text: `[${status}]`, color: state.error ? theme.error : status === "IDLE" ? theme.muted : theme.success },
      { text: `[${state.task?.mode === "explanation" ? "EXPLANATION" : "PLANNED CHANGE"}]`, color: theme.secondary },
      ...(lockCount > 0 ? [{ text: `[${lockMode === "lock" ? "LOCK" : "ALLOW"} ${lockCount}]`, color: lockMode === "lock" ? theme.error : theme.accent }] : []),
      ...(state.task ? [{ text: `r${state.task.revision} · ${state.task.basisRevision.slice(0, 12)}`, color: theme.muted }] : []),
    ],
    right: [{ text: modelInfo.label, color: modelInfo.available ? theme.success : theme.warning }],
  };

  const rows = state.rows.map((row) => {
    const activeRow = entryTouchesNode(row.entry, state.active?.nodeId);
    const failedRow = entryTouchesNode(row.entry, state.failed?.nodeId);
    const entryViewState = entryState(state.task, row, {
      pendingMarks: state.pendingMarks,
      pendingMode: state.pendingMode,
      appliedDiffIds: state.appliedDiffIds,
      live: activeRow || failedRow
        ? { active: activeRow, failed: failedRow, spinner, operation: state.active?.operation }
        : undefined,
    });
    const segments = [];
    if (row.branch) segments.push({ text: row.branch });
    if (entryViewState.indicator) {
      segments.push({ text: entryViewState.indicator, color: entryViewState.color });
      segments.push({ text: " " });
    }
    segments.push({
      text: entryName(row.entry),
      color: row.repositoryOnly ? theme.muted : row.entry.kind === "dir" ? theme.accent : theme.text,
      bold: !row.repositoryOnly,
    });
    if (entryViewState.suffix) {
      segments.push({ text: " " });
      segments.push({ text: entryViewState.suffix, color: theme.muted });
    }
    return { id: row.id, segments, selected: row.id === state.selectedRowId };
  });

  const detail = detailLines(state.task, selectedRow, {
    pendingMarks: state.pendingMarks,
    pendingMode: state.pendingMode,
    appliedDiffIds: state.appliedDiffIds,
    live,
  });

  const choices = candidatesForEntry(state.task, selectedRow?.entry)
    .filter((candidate) => candidate.status === "possible")
    .map((candidate, index) => ({ n: index + 1, candidateId: candidate.id, label: candidate.label }));

  return {
    header,
    hasTask: Boolean(state.task),
    tree: { rows, selectedRowId: state.selectedRowId ?? null, count: rows.length },
    detail,
    panel: {
      busy: state.busy,
      operation: state.operation ?? null,
      error: state.error ? firstLine(state.error) : null,
      message: state.message,
    },
    choices,
  };
}

function frameWithPanelError(error) {
  const frame = buildFrame();
  frame.panel = { ...frame.panel, error };
  return frame;
}

/**
 * The TUI auto-generates approaches for a fresh change task (augment.tsx's
 * initial effect). Hosts want the same, so the shim owns it: after a task
 * starts (or a persisted task is resumed) with a model available and the root
 * still unresolved, run one crystallize in the background, announcing it with
 * progress and frame notifications.
 */
async function maybeAutoGenerate() {
  const snapshot = controller.snapshot();
  const task = snapshot.task;
  const root = task?.nodes[task.rootNodeId];
  if (!modelInfo.available || !task || task.mode !== "change" || !root || root.status !== "unresolved" || root.candidateIds.length || snapshot.busy || autoGenerated.has(task.id)) return;
  autoGenerated.add(task.id);
  notify("neolit/progress", { operation: "Generating approaches", busy: true });
  try {
    await controller.crystallize();
  } catch {
    // dispatch() already recorded the failure in the panel.
  }
  notify("neolit/frame", buildFrame());
}

function newController(directory) {
  const runtime = stub
    ? stubRuntime
    : modelInfo.available
      ? new CliAgentRuntime({ ...runtimeOptions(), directory })
      : undefined;
  return new AugmentTuiController({
    directory,
    runtime,
    persistTasks: process.env.AUGMENT_TUI_TASKS !== "0",
    challengeRounds: config.challengeRounds,
  });
}

// CliAgentRuntime options are computed once here (mirroring bin/augment.tsx).
function runtimeOptions() {
  return {
    backend,
    command: requestedCommand,
    model: config.model,
    draftModel: config.draftModel,
    challengeModel: config.challengeModel,
    server: config.server,
    agent: config.agent,
    timeoutMs: config.timeoutMs,
  };
}

const methods = {
  async initialize(params) {
    const directory = params.directory ?? args.directory ?? process.cwd();
    if (typeof directory !== "string" || !directory.trim()) throw rpcError(-32602, "initialize requires a repository directory.");
    controller = newController(directory);
    autoGenerated = new Set();
    void maybeAutoGenerate();
    return { frame: buildFrame(), model: modelInfo, agent: controller.runtimeAgent() ?? null, directory };
  },

  frame(params) {
    return buildFrame(typeof params.spinner === "string" && params.spinner ? params.spinner : undefined);
  },

  async move(params) {
    controller.move(Number(params.delta) || 0);
    return buildFrame();
  },

  async select(params) {
    if (typeof params.rowId !== "string") throw rpcError(-32602, "select requires rowId.");
    controller.select(params.rowId);
    return buildFrame();
  },

  async start(params) {
    await controller.start(String(params.objective ?? ""));
    void maybeAutoGenerate();
    return buildFrame();
  },

  async explain(params) {
    await controller.explain(String(params.topic ?? ""));
    return buildFrame();
  },

  async rethink(params) {
    await controller.rethink(typeof params.message === "string" ? params.message : undefined);
    return buildFrame();
  },

  async reopen(params) {
    await controller.reopen(String(params.reason ?? ""));
    return buildFrame();
  },

  async stale(params) {
    await controller.markStale(String(params.path ?? ""));
    return buildFrame();
  },

  async choose(params) {
    const row = controller.selectedRow();
    const possible = candidatesForEntry(controller.snapshot().task, row?.entry).filter((candidate) => candidate.status === "possible");
    const candidate = possible[(Number(params.n) || 0) - 1];
    if (!candidate) throw rpcError(-32602, `No approach ${params.n} is open on the selected path.`);
    await controller.selectCandidate(candidate.id);
    return buildFrame();
  },

  async develop() {
    await controller.develop();
    return buildFrame();
  },

  async apply() {
    await controller.applySelected();
    return buildFrame();
  },

  async commit() {
    await controller.commitApplied();
    return buildFrame();
  },

  async lock() {
    await controller.toggleRestriction("lock");
    return buildFrame();
  },

  async allow() {
    await controller.toggleRestriction("allow");
    return buildFrame();
  },

  async configure(params) {
    controller.configureModels({
      model: typeof params.model === "string" && params.model ? params.model : undefined,
      draftModel: typeof params.draftModel === "string" && params.draftModel ? params.draftModel : undefined,
      challengeModel: typeof params.challengeModel === "string" && params.challengeModel ? params.challengeModel : undefined,
    });
    return buildFrame();
  },

  async models() {
    const agent = controller?.runtimeAgent();
    if (!modelInfo.available || !agent) throw rpcError(-32000, "No model runtime is active.");
    try {
      const { availableModels } = await fromDist("tui/setup.js");
      return await availableModels(agent.backendId, agent.command);
    } catch (error) {
      return { models: [], source: `catalog unavailable (${firstLine(error?.message ?? error)}) — type a model id` };
    }
  },

  agent() {
    return controller?.runtimeAgent() ?? null;
  },

  cancel() {
    controller?.cancel();
    return { ok: true };
  },

  async shutdown() {
    return { ok: true };
  },
};

async function handle(message) {
  if (!message || typeof message !== "object" || typeof message.method !== "string") return;
  const isRequest = message.id !== undefined;
  try {
    const handler = methods[message.method];
    if (!handler) throw rpcError(-32601, `Unknown method: ${message.method}`);
    const result = await handler(message.params ?? {});
    if (isRequest) {
      if (message.method === "shutdown") {
        respond(message.id, result);
        setImmediate(() => process.exit(0));
      } else {
        respond(message.id, result);
      }
    }
  } catch (error) {
    if (!isRequest) return;
    if (error && typeof error.code === "number") {
      respondError(message.id, error.code, error.message);
    } else if (controller && message.method !== "initialize") {
      // Controller-level failures surface in the panel exactly like the TUI's
      // run() catch: the frame stays renderable and the error is visible.
      respond(message.id, frameWithPanelError(firstLine(error?.message ?? error)));
    } else {
      respondError(message.id, -32000, firstLine(error?.message ?? error));
    }
  }
}

const lines = readline.createInterface({ input: process.stdin });
lines.on("line", (line) => {
  const trimmed = line.trim();
  if (!trimmed) return;
  let message;
  try {
    message = JSON.parse(trimmed);
  } catch {
    return;
  }
  void handle(message);
});
lines.on("close", () => process.exit(0));
process.stdout.on("error", () => process.exit(0));
